language: python
dist: focal
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.9-dev
before_install:
  - pip install -U pip
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install ".[test]"
script: pytest --cov=marketdata tests/
after_success:
  - codecov
