---
defaultDataSource: "IEXCloud"
defaultFallbackDatasource: "YahooFinance"
datasources:
  - type: "IEXCloud"
    name: "IEXCloud"
    isLibrary: False
    isAuthenticated: True
    baseUrl:
      sandbox: "https://sandbox.iexapis.com"
      production: "https://cloud.iexapis.com"
    authToken:
      sandbox: "env.IEX_SANDBOX_TOKEN"
      production: "env.IEX_PROD_TOKEN"
    environment: "env.IEX_ENVIRONMENT"
    version: "stable"
    resourceMapping:
      summary: "/stock/{}/stats"
      summary_advanced: "/stock/{}/advanced-stats"
    httpFallbackCodes:
      - 401
      - 402
      - 403
      - 404
      - 429
      - 451
      - 500
  - type: "AlphaVantage"
    name: "AlphaVantage"
    isLibrary: False
    isAuthenticated: True
    baseUrl: "https://www.alphavantage.co/query"
    authToken: "env.AV_TOKEN"
    resourceMapping:
      summary: "OVERVIEW"
  - type: "YahooFinance"
    name: "YahooFinance"
    isLibrary: True
    isAuthenticated: False
    resourceMapping:
      summary: "get_info"
